
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/Footer/page";
import Navbar from "@/Navbar/page";
import SplashScreen from "./Components/SplashScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WDaley",
  description: "Generated by WDaley",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <SplashScreen />
            <Navbar />
            {children}
            <Footer />
      </body>
    </html>
  );
}
